---
#
# Ansible managed
#
repository:
  description: Install and configure Graylog log management.
  homepage: https://buluma.github.io/
  topics: monitoring, system", ansible, molecule, tox, playbook
