---

- block:
    - name: "APT Key should be accepted for the MongoDB repo (Ubuntu)"
      ansible.builtin.apt_key:
        url: "{{ graylog_mongodb_ubuntu_key }}"
        state: present

    - name: "Repositories should be updated (Ubuntu)"
      ansible.builtin.apt_repository:
        repo: "{{ graylog_mongodb_ubuntu_repo }}"
        state: "present"
        update_cache: True
  when:
    - ansible_distribution == 'Ubuntu'

- block:
    - name: "APT Key should be accepted for the MongoDB repo (Debian)"
      ansible.builtin.apt_key:
        url: "{{ graylog_mongodb_debian_key }}"
        state: present

    - name: "Repositories should be updated (Debian)"
      ansible.builtin.apt_repository:
        repo: "{{ graylog_mongodb_debian_repo }}"
        state: "present"
        update_cache: True
  when:
    - ansible_distribution == 'Debian'

- name: "MongoDB should be installed"
  ansible.builtin.apt:
    name: "{{ graylog_mongodb_package_name }}"
    state: "present"

- name: "MongoDB service file should be installed"
  ansible.builtin.template:
    src: "mongodb.service-Debian.j2"
    dest: "/lib/systemd/system/mongod.service"
    owner: "root"
    group: "root"
    mode: 0644
  when:
    - use_system_d | bool
    - ansible_distribution == 'Ubuntu'
  notify:
    - "reload systemd configuration"
    - "restart mongod"

- name: "MongoDB should be configured"
  ansible.builtin.template:
    src: "mongodb.conf.j2"
    dest: "/etc/mongod.conf"
    owner: "root"
    group: "root"
    mode: 0644
  notify: "restart mongod"

- meta: "flush_handlers"
- name: "Wait for MongoDB to startup"
  ansible.builtin.wait_for:
    host: "{{graylog_mongodb_bind_ip}}"
    port: "{{graylog_mongodb_bind_port}}"
    delay: 5
    connect_timeout: 1
