---
#
# Ansible managed
#

name: Ansible Molecule

on:
  # Schedule updates (once daily)
  schedule:
    - cron: '13 7 * * *'
  workflow_dispatch:
  push: {branches: ["master", "main"]}

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"
      - name: molecule
<<<<<<< HEAD
        uses: buluma/molecule-action@v5.0.1
=======
        uses: buluma/molecule-action@v4.0.7
>>>>>>> 0e2389eb96f4f86ae3c483158963512aac5269e3
        with:
          command: lint
  test:
    needs:
      - lint
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        config:
          - image: "enterpriselinux"
            tag: "7"
          - image: "enterpriselinux"
            tag: "latest"
          - image: "debian-systemd"
            tag: "latest"
          - image: "debian-systemd"
            tag: "buster"
          - image: "docker-ubuntu-systemd"
            tag: "latest"
          - image: "docker-ubuntu-systemd"
            tag: "bionic"
          - image: "docker-ubuntu-systemd"
            tag: "focal"
          - image: "docker-ubuntu-systemd"
            tag: "jammy"
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"
      - name: disable apparmor for mysql
        run: sudo ln -s /etc/apparmor.d/usr.sbin.mysqld /etc/apparmor.d/disable/
      - name: parse apparmor for mysql
        run: sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld
      - name: molecule
<<<<<<< HEAD
        uses: buluma/molecule-action@v5.0.1
=======
        uses: buluma/molecule-action@v4.0.7
>>>>>>> 0e2389eb96f4f86ae3c483158963512aac5269e3
        with:
          image: ${{ matrix.config.image }}
          tag: ${{ matrix.config.tag }}
